import { ContentCategory } from './types';

export const PERSONAL_INFO = {
    name: 'Muskan Challana',
    title: 'AI Builder · Business Analyst · Vibe Coder',
    bio: "B.Com graduate from Sabarmati University, based in Jaipur. I build AI-powered business tools without writing code — using Claude, Cursor, and Gemini to ship real products fast. Delivered live CRMs and B2B websites for real clients. Campus Ambassador at IIT Delhi. Competed at IIT Madras, IIT Bombay, IIM Kozhikode. Top 3 at IIM Rohtak. McKinsey Forward certified. Previously represented India in swimming and Kathak dance internationally. Open to freelance, internships, and remote opportunities.",
    resumeUrl: '#',
    contactEmail: 'mailto:cmuskan2068@gmail.com',
    socials: {
        linkedin: "https://www.linkedin.com/in/muskan-challana-408234163/",
        github: "https://github.com/challanamuskan",
        instagram: "https://www.instagram.com/muskanchallana",
        facebook: "https://www.facebook.com/share/17J6tNCTvP/?mibextid=wwXIfr"
    }
};

export const PORTFOLIO_DATA: ContentCategory[] = [
    {
        title: 'Projects',
        items: [
            {
                id: 1,
                title: 'Satyam Tex Fabb CRM',
                description: 'Full-stack business CRM for textile machinery parts — live in production.',
                longDescription: 'Built a complete CRM for a 30-year-old textile machinery parts business in Bhilwara, Rajasthan. Features: stock management with OCR bill scanning, customer & lead tracking, automated payment reminders via Email and WhatsApp, purchase orders, MIS with employee attendance, AI email composer, and role-based login. Built with Python, Streamlit, Google Sheets as database. Deployed live on Streamlit Cloud. Built entirely using AI-assisted vibe-coding.',
                imageUrl: 'https://images.unsplash.com/photo-1664575602276-acd073f104c1?q=80&w=2070&auto=format&fit=crop',
                tags: ['Python', 'Streamlit', 'Google Sheets', 'Gmail API', 'WhatsApp', 'OCR', 'Live'],
                year: '2026',
                link: 'https://satyam-tex-fabb.streamlit.app',
            },
            {
                id: 2,
                title: 'National Sales Corporation — B2B Product Catalogue & Lead Gen Site',
                description: 'Full React website with animated logo, product catalogue and RFQ lead capture for a textile machinery parts dealer.',
                longDescription: 'Designed and built a complete B2B digital sales platform for National Sales Corporation — a textile machinery parts dealer. Features an animated SVG logo, full product catalogue across 7 categories (loom parts, spinning spares, bearings, knitting components), an RFQ lead capture form, AI chatbot assistant, and a gated content section. Built with React, TypeScript, and Vite. Frontend complete — demonstrates ability to deliver professional B2B web products for the textile industry.',
                imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2070&auto=format&fit=crop',
                tags: ['React', 'TypeScript', 'Vite', 'B2B', 'Textile Industry', 'Lead Gen'],
                year: '2026',
                link: 'https://github.com/challanamuskan/person_portfolio',
            },
            {
                id: 3,
                title: 'PitPilot — F1 Race Strategy AI',
                description: 'AI-powered Formula 1 pit stop and race strategy assistant.',
                longDescription: 'An AI-driven analytics dashboard for Formula 1 race operations. PitPilot analyses race data to recommend optimal pit stop windows, tyre strategies, and overtaking opportunities. Built for motorsport enthusiasts who want to understand the strategy layer behind race decisions.',
                imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=2070&auto=format&fit=crop',
                tags: ['Python', 'AI', 'Data Analytics', 'F1', 'Strategy'],
                year: '2025',
                link: 'https://github.com/challanamuskan/PitPilot-AI-Driven-Race-Ops-Pit-Strategy-Assistant',
            },
            {
                id: 4,
                title: 'Student Legal Gateway',
                description: 'RAG-based AI legal assistant for international students.',
                longDescription: 'A RAG-based AI assistant that helps international students understand their legal rights, visa conditions, and university policies. Simplifies complex legal documents into plain English answers using vector search and conversational AI.',
                imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=2070&auto=format&fit=crop',
                tags: ['RAG', 'AI', 'Python', 'Legal Tech', 'Students'],
                year: '2025',
                link: 'https://github.com/challanamuskan/uni_student_help',
            },
            {
                id: 5,
                title: 'GenAI Portfolio',
                description: 'Collection of generative AI projects built with Gemini, Claude and LLMs.',
                longDescription: 'A curated collection of generative AI experiments — from prompt engineering to full AI-powered applications. Demonstrates practical use of LLMs including Google Gemini and Anthropic Claude across business, creative, and analytical use cases.',
                imageUrl: 'https://images.unsplash.com/photo-1677756119517-756a188d2d94?q=80&w=2070&auto=format&fit=crop',
                tags: ['Gemini', 'Claude', 'GenAI', 'LLMs', 'Prompt Engineering'],
                year: '2025',
                link: 'https://github.com/challanamuskan/genai-portfolio',
            },
        ]
    },
    {
        title: 'Professional Experience',
        items: [
            {
                id: 6,
                title: 'Freelance AI Builder & Vibe Coder',
                description: 'Independent · Jaipur, India · 2025–Present',
                longDescription: 'Building AI-powered business tools for SMEs using vibe-coding — shipping real products with Claude, Cursor, and Gemini. Delivered Satyam Tex Fabb CRM (live in production) and NSC B2B website. Building pipeline of AI tools for Rajasthan-based textile businesses.',
                imageUrl: 'https://images.unsplash.com/photo-1664575602276-acd073f104c1?q=80&w=2070&auto=format&fit=crop',
                tags: ['AI Tools', 'Vibe Coding', 'CRM', 'React', 'Python', 'Freelance'],
                year: '2025-Present',
            },
            {
                id: 7,
                title: "Campus Ambassador — IIT Delhi eDCon'26",
                description: 'IIT Delhi · Campus Ambassador · 2026',
                longDescription: "Selected as Campus Ambassador for eDCon'26 — the entrepreneurship and design conclave of IIT Delhi. Responsible for promoting the event, driving registrations, and representing IIT Delhi's entrepreneurship cell on campus. A competitive selection reflecting strong communication and network-building skills.",
                imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=2086&auto=format&fit=crop',
                tags: ['IIT Delhi', 'Campus Ambassador', 'Entrepreneurship', 'Leadership'],
                year: '2026',
            },
            {
                id: 8,
                title: 'Sales & Marketing Coordinator',
                description: 'Lagardère AWPL · Australia · 2022–2024',
                longDescription: 'Transformed daily customer data into actionable Excel insights, launching promotions that lifted sales by 15%. Optimized inventory with pivot tables, cutting stock variances by 22%. Crafted tailored pitches for luxury buyers, boosting upsell rates by 20%. Built weekly Google Sheets dashboards for real-time team insights.',
                imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071&auto=format&fit=crop',
                tags: ['Data Analysis', 'Excel', 'Inventory', 'Sales Strategy', 'Australia'],
                year: '2022-2024',
            },
            {
                id: 9,
                title: 'Sales Representative',
                description: 'Nespresso Boutique · Australia · 2023',
                longDescription: 'Gleaned insights from 100+ daily demos, lifting conversion rates by 25%. Created Excel trackers for transactions and inventory, crafting monthly reports that guided store decisions.',
                imageUrl: 'https://images.unsplash.com/photo-1580920469275-653531b36965?q=80&w=2070&auto=format&fit=crop',
                tags: ['Sales', 'Customer Insights', 'Excel', 'Reporting'],
                year: '2023',
            },
        ]
    },
    {
        title: 'Key Achievements',
        items: [
            {
                id: 10,
                title: 'McKinsey Forward Certified',
                description: 'Elite leadership & problem solving program by McKinsey & Company.',
                longDescription: 'Completed the McKinsey Forward Program — a highly selective program by McKinsey & Company focused on leadership, structured problem solving, and building skills for the future of work. Selected from a global pool of applicants.',
                imageUrl: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=2070&auto=format&fit=crop',
                tags: ['McKinsey', 'Leadership', 'Problem Solving', 'Global'],
                year: '2025',
                modalStyle: 'achievement',
            },
            {
                id: 11,
                title: 'IIT Madras — SHAastra 2026 (×4 Certificates)',
                description: "4 competition certificates from IIT Madras's annual technical fest.",
                longDescription: "Received 4 certificates from SHAastra 2026 — the annual technical and management festival of IIT Madras, one of India's premier engineering institutions. Competed across multiple categories, demonstrating consistent performance at the highest level of student competitions in India.",
                imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=2086&auto=format&fit=crop',
                tags: ['IIT Madras', 'SHAastra', 'Competition', '4 Certificates'],
                year: '2026',
                modalStyle: 'achievement',
            },
            {
                id: 12,
                title: 'IIT Bombay — Techfest 2025 (×2 Certificates)',
                description: "2 certificates from Asia's largest science and technology festival.",
                longDescription: "Received 2 certificates from Techfest 2025 — Asia's largest science and technology festival, hosted by IIT Bombay. Competing at Techfest places you among the brightest student minds from across Asia.",
                imageUrl: 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?q=80&w=2070&auto=format&fit=crop',
                tags: ['IIT Bombay', 'Techfest', 'Competition', "Asia's Largest Fest"],
                year: '2025',
                modalStyle: 'achievement',
            },
            {
                id: 13,
                title: "IIM Kozhikode — Backwaters'26 (×4 Certificates)",
                description: "4 certificates from IIM Kozhikode's annual management festival.",
                longDescription: "Received 4 certificates from Backwaters'26 — the annual management and cultural festival of IIM Kozhikode (IIMK), one of India's top management institutions. Competing across 4 events reflects both versatility and consistent performance.",
                imageUrl: 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?q=80&w=2070&auto=format&fit=crop',
                tags: ['IIM Kozhikode', 'Backwaters', 'Management', '4 Certificates'],
                year: '2026',
                modalStyle: 'achievement',
            },
            {
                id: 14,
                title: 'Top 3 — IIM Rohtak National Competition',
                description: '3rd place in a national-level competition at IIM Rohtak.',
                longDescription: "Achieved 3rd position in a national-level competition organized by IIM Rohtak — one of India's premier management institutions. Competed against participants from top universities across India.",
                imageUrl: 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?q=80&w=2070&auto=format&fit=crop',
                tags: ['IIM Rohtak', 'National', 'Top 3', 'Competition'],
                year: '2025',
                modalStyle: 'achievement',
            },
            {
                id: 15,
                title: 'Represented India — Swimming (International)',
                description: 'Twice represented India in freestyle swimming internationally.',
                longDescription: 'Twice represented India in freestyle swimming at international competitions between 2014 and 2016. Discipline, peak performance, and representing your country on a global stage — the same mindset applied to every project.',
                imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b17415?q=80&w=2070&auto=format&fit=crop',
                tags: ['Swimming', 'India', 'International', 'Athlete'],
                year: '2014-2016',
                modalStyle: 'achievement',
            },
            {
                id: 16,
                title: 'Represented India — Classical Kathak Dance',
                description: 'Twice represented India in Kathak dance internationally.',
                longDescription: 'Twice represented India in the classical dance form of Kathak from 2012 to 2014. Blending intricate footwork, expressive storytelling, and cultural heritage in international performances.',
                imageUrl: 'https://images.unsplash.com/photo-1621335828751-84224571d072?q=80&w=1974&auto=format&fit=crop',
                tags: ['Kathak', 'Dance', 'India', 'International'],
                year: '2012-2014',
                modalStyle: 'achievement',
            },
        ]
    },
    {
        title: 'Education',
        items: [
            {
                id: 17,
                title: 'Sabarmati University',
                description: 'Bachelor of Commerce (B.Com) — Completed',
                longDescription: 'Completed B.Com from Sabarmati University, Ahmedabad. Strong foundation in business, accounting, economics, and finance — simultaneously building AI tools and freelance products.',
                imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=2072&auto=format&fit=crop',
                tags: ['B.Com', 'Business', 'Economics', 'Finance'],
                year: 'Completed',
            },
            {
                id: 18,
                title: 'Torrens University, Adelaide',
                description: 'Bachelor of Business Information Systems — On Hold',
                longDescription: 'Pursued BBIS at Torrens University, Australia. Gained expertise in data analytics, predictive modelling, Python, R, and SPSS. Currently on hold while building freelance practice in India.',
                imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=2070&auto=format&fit=crop',
                tags: ['Data Analytics', 'Python', 'R', 'Australia', 'Business Systems'],
                year: 'On Hold',
            },
        ]
    },
    {
        title: 'Certifications & Badges',
        items: [
            {
                id: 19,
                title: 'McKinsey Forward — McKinsey & Company',
                description: 'Leadership and structured problem solving certification.',
                longDescription: 'Completed McKinsey Forward in 2025, focused on structured problem solving, communication, and leadership capability development.',
                imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2070&auto=format&fit=crop',
                tags: ['McKinsey', 'Leadership', 'Problem Solving'],
                year: '2025',
            },
            {
                id: 20,
                title: 'Nestlé YEP Academy ×4 + FoodTech ×1',
                description: '5 total Nestlé certifications in entrepreneurship and innovation.',
                longDescription: 'Completed five Nestlé certifications between 2023 and 2024, including YEP Academy tracks and a FoodTech course.',
                imageUrl: 'https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?q=80&w=2070&auto=format&fit=crop',
                tags: ['Nestlé', 'YEP', 'FoodTech', 'Entrepreneurship'],
                year: '2023-2024',
            },
            {
                id: 21,
                title: 'Google Data Analytics Professional Certificate — Coursera',
                description: 'Professional data analytics certification.',
                longDescription: 'Completed Google Data Analytics Professional Certificate in 2022 with practical skills in cleaning, analysis, and visualization.',
                imageUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?q=80&w=2070&auto=format&fit=crop',
                tags: ['Google', 'Data Analytics', 'Coursera'],
                year: '2022',
            },
            {
                id: 22,
                title: 'Cisco Networking Academy ×7',
                description: 'SQL, analytics, Excel, and networking certifications.',
                longDescription: 'Completed seven Cisco Networking Academy certifications in SQL, data analytics, dashboarding, networking basics, and Excel workflows.',
                imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop',
                tags: ['Cisco', 'SQL', 'Analytics', 'Networking', 'Excel'],
                year: '2025',
            },
            {
                id: 23,
                title: 'HP LIFE — Data Science & AI for Business',
                description: 'Business-focused data science and AI certification.',
                longDescription: 'Completed HP LIFE certifications in Data Science and AI for Business in 2025, with emphasis on practical business applications.',
                imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
                tags: ['HP LIFE', 'Data Science', 'AI', 'Business'],
                year: '2025',
            },
            {
                id: 24,
                title: 'BRICS Mathematics Competition Stage 2',
                description: 'Advanced mathematics competition qualifier.',
                longDescription: 'Qualified for Stage 2 in the BRICS Mathematics Competition in 2024, demonstrating analytical and quantitative problem-solving skills.',
                imageUrl: 'https://images.unsplash.com/photo-1635372722656-389f87a941b7?q=80&w=2070&auto=format&fit=crop',
                tags: ['BRICS', 'Mathematics', 'Competition'],
                year: '2024',
            },
        ]
    },
    {
        title: 'Skills',
        items: [
            {
                id: 25,
                title: 'AI & Vibe Coding',
                description: 'Claude, Cursor, Gemini, Prompt Engineering',
                longDescription: 'Builds production-ready solutions using AI-first workflows, prompt engineering, and rapid iterative delivery.',
                imageUrl: 'https://images.unsplash.com/photo-1677756119517-756a188d2d94?q=80&w=2070&auto=format&fit=crop',
                tags: ['Claude', 'Cursor', 'Gemini', 'Prompt Engineering'],
                year: 'Core Skill',
            },
            {
                id: 26,
                title: 'Data & Analytics',
                description: 'Python, R, SQL, Excel, Streamlit',
                longDescription: 'Applies data analysis and automation across reporting, modeling, and dashboard workflows for business decision-making.',
                imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
                tags: ['Python', 'R', 'SQL', 'Excel', 'Streamlit'],
                year: 'Core Skill',
            },
            {
                id: 27,
                title: 'Business Operations',
                description: 'CRM, MIS, Inventory, Sales, Marketing',
                longDescription: 'Hands-on operational expertise spanning CRM setup, MIS, inventory control, sales systems, and marketing execution.',
                imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2070&auto=format&fit=crop',
                tags: ['CRM', 'MIS', 'Inventory', 'Sales', 'Marketing'],
                year: 'Core Skill',
            },
            {
                id: 28,
                title: 'Communication & Leadership',
                description: 'Presentations, multilingual, debate captain, mentoring',
                longDescription: 'Strong communication and leadership skills built through campus roles, competition participation, debate, and mentoring.',
                imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=2070&auto=format&fit=crop',
                tags: ['Presentations', 'Multilingual', 'Debate', 'Mentoring', 'Leadership'],
                year: 'Core Skill',
            },
        ]
    },
    {
        title: 'Volunteering',
        items: [
            {
                id: 29,
                title: 'NGO Volunteer',
                description: 'India (2024-2025)',
                longDescription: 'Supported NGO initiatives in India focused on community development and social impact activities.',
                imageUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=2070&auto=format&fit=crop',
                tags: ['NGO', 'Community', 'Social Impact'],
                year: '2024-2025',
            },
            {
                id: 30,
                title: 'University Mentor',
                description: 'UniSA (2022-2024)',
                longDescription: 'Mentored students at the University of South Australia, helping them adapt academically and socially.',
                imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=2070&auto=format&fit=crop',
                tags: ['UniSA', 'Mentoring', 'Student Support'],
                year: '2022-2024',
            },
        ]
    }
];
