import { ContentCategory } from './types';

export const PERSONAL_INFO = {
    name: 'Muskan Challana',
    title: 'AI Builder · Vibe Coder · Business Analyst',
    bio: "Commerce graduate from Sabarmati University, based in Bhilwara, Rajasthan. I build AI-powered business tools without writing code — using Claude, Cursor, and Gemini to ship real products fast. Delivered a live CRM for a 30-year textile machinery business. Competed at IIT Madras, IIT Bombay, IIT Delhi, IIM Kozhikode, IIM Indore & IIM Rohtak. Represented India internationally in swimming and Kathak. McKinsey Forward certified. Open to freelance, internships and remote roles.",
    resumeUrl: 'https://www.linkedin.com/in/muskan-challana-408234163/',
    contactEmail: 'mailto:cmuskan2068@gmail.com',
    socials: {
        linkedin: 'https://www.linkedin.com/in/muskan-challana-408234163/',
        github: 'https://github.com/challanamuskan',
        instagram: 'https://www.instagram.com/muskanchallana',
        facebook: 'https://www.facebook.com/share/17J6tNCTvP/?mibextid=wwXIfr',
    },
};

export const PORTFOLIO_DATA: ContentCategory[] = [
    {
        title: 'Projects',
        items: [
            {
                id: 'crm',
                title: 'Satyam Tex Fabb CRM',
                subtitle: 'Full-stack business CRM — live in production',
                description: 'Built a complete CRM for a 30-year-old textile machinery parts business in Bhilwara. Stock management with OCR bill scanning, customer & lead tracking, payment reminders via Email and WhatsApp, purchase orders, MIS with employee attendance, role-based login, live calendar. Python + Streamlit + Google Sheets. Live now.',
                tags: ['Python', 'Streamlit', 'Google Sheets', 'Gmail API', 'WhatsApp', 'OCR', 'Live'],
                year: '2026',
                link: 'https://satyam-tex-fabb.streamlit.app',
                imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'nsc',
                title: 'NSC — B2B Product Catalogue & Lead Gen',
                subtitle: 'React website for a textile machinery parts dealer',
                description: 'Full B2B product catalogue and lead generation website for National Sales Corporation. Animated SVG logo, 7-category product catalogue (loom parts, spinning spares, bearings, knitting components), RFQ inquiry form, AI chatbot. React + TypeScript + Vite.',
                tags: ['React', 'TypeScript', 'Vite', 'B2B', 'Lead Generation', 'Textile'],
                year: '2025',
                link: 'https://github.com/challanamuskan',
                imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'pitpilot',
                title: 'PitPilot — F1 Race Strategy AI',
                subtitle: 'AI-powered Formula 1 pit stop and race strategy assistant',
                description: 'AI-driven analytics dashboard for Formula 1 race operations. Recommends optimal pit stop windows, tyre strategies, and overtaking opportunities based on live race data. Built with Python and data visualisation libraries.',
                tags: ['Python', 'AI', 'Data Analytics', 'F1', 'Strategy'],
                year: '2025',
                link: 'https://github.com/challanamuskan/PitPilot-AI-Driven-Race-Ops-Pit-Strategy-Assistant',
                imageUrl: 'https://images.unsplash.com/photo-1504707748692-419802cf939d?q=80&w=2047&auto=format&fit=crop',
            },
            {
                id: 'legal',
                title: 'Student Legal Gateway',
                subtitle: 'AI legal assistant for international students',
                description: 'RAG-based AI assistant helping international students understand visa conditions, legal rights, and university policies in plain English. Uses vector search and conversational AI to answer complex legal questions instantly.',
                tags: ['RAG', 'AI', 'Python', 'Legal Tech', 'Students'],
                year: '2025',
                link: 'https://github.com/challanamuskan/uni_student_help',
                imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=2070&auto=format&fit=crop',
            },
        ],
    },

    {
        title: 'Experience',
        items: [
            {
                id: 'freelance',
                title: 'Freelance AI Builder & Vibe Coder',
                subtitle: 'Independent · Bhilwara, Rajasthan · 2025–Present',
                description: 'Building AI-powered business tools for SMEs using vibe-coding — shipping real products with Claude, Cursor, and Gemini without writing code manually. Delivered Satyam Tex Fabb CRM (live) and NSC B2B website. Building pipeline of similar tools for Rajasthan-based businesses and global freelance platforms.',
                tags: ['AI Tools', 'Vibe Coding', 'CRM', 'Freelance', 'Python', 'React'],
                year: '2025–Present',
                imageUrl: 'https://images.unsplash.com/photo-1664575602276-acd073f104c1?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'edcon',
                title: "Campus Ambassador — eDCon'26",
                subtitle: 'IIT Delhi · 2025–2026',
                description: "Selected as Campus Ambassador for eDCon'26 by IIT Delhi — one of India's premier entrepreneurship and design conferences. Responsible for outreach, registrations, and representing the event at Sabarmati University.",
                tags: ['IIT Delhi', 'Campus Ambassador', 'Entrepreneurship', 'Leadership'],
                year: '2025–2026',
                imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=2086&auto=format&fit=crop',
            },
            {
                id: 'oval',
                title: 'Hospitality & Events — Bartender',
                subtitle: 'Adelaide Oval & Adelaide Convention Centre · Australia · 2022–2024',
                description: "Delivered premium hospitality and bartending at two of Adelaide's most prestigious venues. Adelaide Oval hosts major international cricket and AFL events (50,000+ capacity). Adelaide Convention Centre hosts large-scale corporate and international conferences. Managed bar operations and guest service under high-pressure, high-volume event conditions.",
                tags: ['Hospitality', 'Bartending', 'Events Management', 'Adelaide', 'Australia'],
                year: '2022–2024',
                imageUrl: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?q=80&w=2029&auto=format&fit=crop',
            },
            {
                id: 'flinders',
                title: 'COVID Concierge',
                subtitle: 'Flinders Medical Centre · Adelaide, Australia · 2022–2023',
                description: "Served as COVID Concierge at Flinders Medical Centre — one of South Australia's largest public hospitals. Managed patient and visitor screening, enforced infection control protocols, and provided guidance in a high-stress healthcare environment. Developed strong empathy, crisis communication, and compliance skills.",
                tags: ['Healthcare', 'Hospital', 'Patient Support', 'Crisis Management', 'Australia'],
                year: '2022–2023',
                imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2053&auto=format&fit=crop',
            },
            {
                id: 'lagardere',
                title: 'Sales & Marketing Coordinator',
                subtitle: 'Lagardère AWPL · Australia · 2022–2024',
                description: 'Transformed daily customer data into Excel insights, lifting sales by 15%. Cut stock variances by 22% with pivot table inventory optimisation. Boosted upsell rates by 20% with tailored luxury buyer pitches. Built weekly Google Sheets dashboards for real-time team insights.',
                tags: ['Data Analysis', 'Excel', 'Inventory', 'Sales Strategy', 'Australia'],
                year: '2022–2024',
                imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071&auto=format&fit=crop',
            },
            {
                id: 'mentor',
                title: 'Student Mentor',
                subtitle: 'University of South Australia · 2022–2024',
                description: 'Mentored international students navigating Australian university life — academic, cultural, and personal transitions. Part of the formal UniSA peer mentoring programme for 2 years.',
                tags: ['Mentoring', 'Leadership', 'International Students', 'UniSA'],
                year: '2022–2024',
                imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?q=80&w=2070&auto=format&fit=crop',
            },
        ],
    },

    {
        title: 'Achievements',
        items: [
            {
                id: 'mckinsey',
                title: 'McKinsey Forward Certified',
                subtitle: 'McKinsey & Company · 2025',
                description: 'Completed McKinsey Forward — a highly selective global programme by McKinsey & Company focused on leadership, structured problem solving, and future-ready professional skills.',
                tags: ['McKinsey', 'Leadership', 'Problem Solving', 'Global', 'Selective'],
                year: '2025',
                modalStyle: 'achievement',
                imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'iim-rohtak',
                title: 'Top 3 — IIM Rohtak National Competition',
                subtitle: 'IIM Rohtak · 2025',
                description: "Secured 3rd place in a national-level competition at IIM Rohtak — one of India's premier management institutes. Competed against participants from top universities across India.",
                tags: ['IIM Rohtak', 'National', 'Top 3', 'Management'],
                year: '2025',
                modalStyle: 'achievement',
                imageUrl: 'https://images.unsplash.com/photo-1523580846011-d3a5bc86b40?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'iit-madras',
                title: 'IIT Madras — SHAastra 2026 × 4',
                subtitle: 'ADI Reverse Engineering · Embedded Programming · E-Contest · Petri Dish',
                description: "Received 4 certificates from SHAastra 2026 — IIT Madras's flagship technical festival and one of India's most competitive tech fests. Competed in ADI Reverse Engineering Challenge, Embedded Programming Challenge, E-Contest, and Petri Dish Challenge.",
                tags: ['IIT Madras', 'SHAastra 2026', 'Engineering', 'Technology', '× 4'],
                year: '2026',
                modalStyle: 'achievement',
                imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=2086&auto=format&fit=crop',
            },
            {
                id: 'iit-bombay',
                title: 'IIT Bombay — Techfest 2025 × 2',
                subtitle: "Capture The Flag · Agrowsera TRBS · Asia's Largest Tech Fest",
                description: "2 certificates from Techfest 2025 at IIT Bombay — Asia's largest science and technology festival. Competed in Capture The Flag (cybersecurity) and Agrowsera: The Red Brick Summit agri-innovation challenge.",
                tags: ['IIT Bombay', 'Techfest 2025', "Asia's Largest", 'Cybersecurity', '× 2'],
                year: '2025',
                modalStyle: 'achievement',
                imageUrl: 'https://images.unsplash.com/photo-1581093458791-9a6685c2e505?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'iim-kozhikode',
                title: "IIM Kozhikode — Backwaters'26 × 4",
                subtitle: 'IPL Fantasy · Avatar CEO · Kotler Sutra · Project Horizon',
                description: "4 certificates from Backwaters'26 at IIM Kozhikode — consistently ranked among India's top 5 management institutes. Competed in IPL Fantasy: Build Your Dream Team, Avatar: The Ultimate CEO, Kotler Sutra Marketing Case Competition, and Project Horizon: GPAI Case Competition.",
                tags: ['IIM Kozhikode', "Backwaters'26", 'Marketing', 'Strategy', '× 4'],
                year: '2026',
                modalStyle: 'achievement',
                imageUrl: 'https://images.unsplash.com/photo-1523580846011-d3a5bc86b40?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'iim-indore',
                title: 'IIM Indore — IRIS 2026',
                subtitle: 'Ashwamesha Leadership · Finance League: Equity Pitch',
                description: "Competed in IRIS 2026 — IIM Indore's flagship management fest. Events: Ashwamesha Legacy Leadership Competition and Finance League: Equity Pitch Challenge.",
                tags: ['IIM Indore', 'IRIS 2026', 'Leadership', 'Finance', 'Equity'],
                year: '2026',
                modalStyle: 'achievement',
                imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'unstop',
                title: '83 Competition Certificates — Unstop',
                subtitle: 'IITs · IIMs · Hackathons · Case Studies · 2025–2026',
                description: '83 verified participation certificates on Unstop — spanning hackathons at IIT Madras and IIT Bombay, case competitions at IIM Kozhikode, IIM Indore and IIM Rohtak, national data analytics challenges, cybersecurity contests, HR hackathons, startup pitch events, and marketing case studies.',
                tags: ['83 Certificates', 'IIT', 'IIM', 'Hackathons', 'National', 'Verified'],
                year: '2025–2026',
                modalStyle: 'achievement',
                imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'swimming',
                title: 'Represented India — Freestyle Swimming',
                subtitle: 'International Competition · 2014–2016',
                description: 'Twice represented India in freestyle swimming at international competitions. Selected at the highest national level from a young age.',
                tags: ['Swimming', 'India', 'International', 'Athlete', 'Freestyle'],
                year: '2014–2016',
                modalStyle: 'achievement',
                imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b17415?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'kathak',
                title: 'Represented India — Classical Kathak',
                subtitle: 'International Performance · 2012–2014',
                description: "Twice represented India in classical Kathak dance at international performances. Performed on international stages representing India's classical arts.",
                tags: ['Kathak', 'Classical Dance', 'India', 'International', 'Arts'],
                year: '2012–2014',
                modalStyle: 'achievement',
                imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=2069&auto=format&fit=crop',
            },
        ],
    },

    {
        title: 'Certifications',
        items: [
            {
                id: 'cert-mckinsey',
                title: 'McKinsey Forward',
                subtitle: 'McKinsey & Company · 2025',
                description: 'Highly selective global leadership and problem-solving programme by McKinsey & Company.',
                tags: ['McKinsey', 'Leadership', 'Global', 'Selective'],
                year: '2025',
                imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'cert-nestle',
                title: 'Nestlé YEP Academy × 4 + FoodTech',
                subtitle: 'Nestlé · 2023–2024',
                description: '5 certifications from Nestlé: 4 from the Young Entrepreneurs Program Academy covering entrepreneurship, marketing, and business strategy, plus 1 FoodTech industry course.',
                tags: ['Nestlé', 'YEP', 'Entrepreneurship', 'FoodTech', '× 5'],
                year: '2023–2024',
                imageUrl: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'cert-google',
                title: 'Google Data Analytics',
                subtitle: 'Google via Coursera · 2022',
                description: 'Professional certificate covering data cleaning, analysis, visualisation, and storytelling using SQL, R, and Tableau.',
                tags: ['Google', 'Data Analytics', 'SQL', 'R', 'Coursera'],
                year: '2022',
                imageUrl: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?q=80&w=2027&auto=format&fit=crop',
            },
            {
                id: 'cert-cisco',
                title: 'Cisco Networking Academy × 7',
                subtitle: 'Cisco · 2025',
                description: '7 certifications: Networking Basics, Data Analytics Essentials, SQL Basics, Transforming Data with Excel, Dashboarding Basics, Ethical Use of Data, Project Portfolio.',
                tags: ['Cisco', 'SQL', 'Analytics', 'Excel', 'Networking', '× 7'],
                year: '2025',
                imageUrl: 'https://images.unsplash.com/photo-1593435713583-2effa2f6472f?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'cert-hp',
                title: 'HP LIFE × 2',
                subtitle: 'HP Foundation · 2025',
                description: "Data Science & Analytics and AI for Business Professionals — HP Foundation's global learning platform.",
                tags: ['HP LIFE', 'AI', 'Data Science', 'Business'],
                year: '2025',
                imageUrl: 'https://images.unsplash.com/photo-1677756119517-756a188d2d94?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'cert-unstop',
                title: '83 Competition Certificates — Unstop',
                subtitle: 'IITs · IIMs · Hackathons · Case Studies · 2025–2026',
                description: '83 verified participation certificates from competitions hosted by IIT Madras, IIT Bombay, IIM Kozhikode, IIM Indore, IIM Rohtak, plus national hackathons, data analytics challenges, and startup pitch events.',
                tags: ['83 Certificates', 'IIT', 'IIM', 'Hackathons', 'Verified'],
                year: '2025–2026',
                imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=2070&auto=format&fit=crop',
            },
        ],
    },

    {
        title: 'Education',
        items: [
            {
                id: 'sabarmati',
                title: 'Sabarmati University',
                subtitle: 'B.Com · Bhilwara, Rajasthan · Graduated',
                description: 'Bachelor of Commerce. Strong foundation in business, economics, finance, and management. Supplemented with extensive competitive participation at IITs and IIMs across India.',
                tags: ['B.Com', 'Business', 'Economics', 'Finance', 'Rajasthan'],
                year: '2022–2025',
                imageUrl: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?q=80&w=2074&auto=format&fit=crop',
            },
            {
                id: 'australia',
                title: 'International Study & Work Experience',
                subtitle: 'Adelaide, Australia · 2022–2024',
                description: 'Lived and worked independently in Adelaide, Australia for 2 years. Gained hands-on professional experience across hospitality and events (Adelaide Oval, Adelaide Convention Centre), healthcare (Flinders Medical Centre), luxury retail (Lagardère), and university mentoring (UniSA). Developed cross-cultural communication, resilience, and global work ethic.',
                tags: ['Australia', 'International Experience', 'Adelaide', 'Cross-Cultural', 'Independent'],
                year: '2022–2024',
                imageUrl: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'kenbridge',
                title: 'Kenbridge School, Kota',
                subtitle: 'High School · Top 10% Maths & Economics · 2020',
                description: "Completed high school at Kenbridge School, Kota — one of India's top academic cities. Ranked in top 10% for Mathematics and Economics. Served as Debate Captain.",
                tags: ['Mathematics', 'Economics', 'Debate Captain', 'Kota'],
                year: '2020',
                imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?q=80&w=2070&auto=format&fit=crop',
            },
        ],
    },

    {
        title: 'Skills',
        items: [
            {
                id: 'skill-ai',
                title: 'AI & Vibe Coding',
                subtitle: 'Claude, Cursor, Gemini, Copilot, Prompt Engineering',
                description: 'Building production-grade apps without writing code manually. Shipped a live CRM, B2B website, and multiple AI tools using vibe-coding with Claude, GitHub Copilot, and Gemini.',
                tags: ['Claude', 'Cursor', 'Gemini', 'Copilot', 'Prompt Engineering', 'Vibe Coding'],
                imageUrl: 'https://images.unsplash.com/photo-1677756119517-756a188d2d94?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'skill-data',
                title: 'Data & Analytics',
                subtitle: 'Python, R, SQL, Excel, Streamlit, Google Sheets',
                description: 'End-to-end data work from raw cleaning to live dashboards. Used Python + Streamlit to build live business tools. Advanced Excel and SQL for business analysis.',
                tags: ['Python', 'R', 'SQL', 'Excel', 'Streamlit', 'Dashboards'],
                imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'skill-web',
                title: 'Web Development',
                subtitle: 'React, TypeScript, Vite, HTML/CSS',
                description: 'Building modern web interfaces with React and TypeScript. Delivered an animated B2B product catalogue and a Netflix-style portfolio. Comfortable with component architecture and Vercel deployment.',
                tags: ['React', 'TypeScript', 'Vite', 'HTML', 'CSS', 'Vercel'],
                imageUrl: 'https://images.unsplash.com/photo-1593720219276-0b1eacd0aef4?q=80&w=2071&auto=format&fit=crop',
            },
            {
                id: 'skill-business',
                title: 'Business Operations',
                subtitle: 'CRM, MIS, Sales, Marketing, Hospitality, Events',
                description: 'Real-world operations across India (AI tools, freelance) and Australia (luxury retail, major events venues, healthcare). Built tools that replaced Tally + WhatsApp workflows for SMEs.',
                tags: ['CRM', 'MIS', 'Sales', 'Marketing', 'Hospitality', 'Events'],
                imageUrl: 'https://images.unsplash.com/photo-1664575602276-acd073f104c1?q=80&w=2070&auto=format&fit=crop',
            },
        ],
    },

    {
        title: 'Volunteering',
        items: [
            {
                id: 'vol-ngo',
                title: 'NGO Volunteer',
                subtitle: 'Rajasthan, India · 2024–2025',
                description: 'Contributed time to community development and education initiatives across Rajasthan. Worked with local NGOs supporting underprivileged communities.',
                tags: ['NGO', 'Community', 'Education', 'Rajasthan'],
                year: '2024–2025',
                imageUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=2070&auto=format&fit=crop',
            },
            {
                id: 'vol-mentor',
                title: 'University Mentor',
                subtitle: 'University of South Australia · 2022–2024',
                description: 'Mentored international students navigating Australian university life through academic and cultural transitions for 2 years.',
                tags: ['Mentoring', 'UniSA', 'International Students', 'Leadership'],
                year: '2022–2024',
                imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=2069&auto=format&fit=crop',
            },
        ],
    },
];
