import { ContentCategory } from './types';

export const PERSONAL_INFO = {
  name: 'Muskan Challana',
  title: 'Founder, Nexivo — AI-powered ops for Indian SMEs | DPIIT Registered | 2 Paying Clients',
  bio: "I build and deploy AI-powered business systems for real Indian SMEs — not demos, not prototypes. Nexivo (DPIIT-registered) delivers three products: a full CRM with WhatsApp automation, an audit platform, and workflow automation. In ~3 months from zero coding background, I shipped two paying clients a live CRM that saves 8+ hours of manual admin per week. I use Claude, Cursor, and Supabase to build what used to take a team.",
  resumeUrl: 'https://www.linkedin.com/in/muskan-challana-408234163/',
  contactEmail: 'mailto:cmuskan2068@gmail.com',
  socials: {
    linkedin: 'https://www.linkedin.com/in/muskan-challana-408234163/',
    github: 'https://github.com/challanamuskan',
    instagram: 'https://www.instagram.com/muskanchallana',
    facebook: 'https://www.facebook.com/share/17J6tNCTvP/?mibextid=wwXIfr',
  },
};

export const PORTFOLIO_DATA: ContentCategory[] = [
  {
    title: 'Projects',
    items: [
      {
        id: 'nexivo-crm',
        title: 'Nexivo CRM',
        subtitle: 'AI-powered pipeline automation for SMEs — live with paying clients',
        description: 'Full-stack CRM for Indian manufacturing SMEs. 2,000+ part inventory with OCR bill scanning, bulk CSV/XLS import (400-row batches), Excel/PDF export, Tally import, admin controls, intelligent API caching, automated low-stock email alerts (1st & 15th), supplier price history, stock search, part image gallery, customer & lead tracking, payment reminders, purchase orders, MIS analytics, employee attendance, role-based login, WhatsApp automation. Python + Streamlit + Supabase PostgreSQL + Gmail API. Live in daily production use with 2 paying clients.',
        tags: ['Python', 'Streamlit', 'Supabase', 'Gmail API', 'WhatsApp', 'OCR', 'DPIIT', 'Live'],
        year: '2026',
        link: 'https://github.com/challanamuskan/indian-sme-crm-template',
        liveUrl: 'https://crm-template.streamlit.app',
        imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'nexivo-audit',
        title: 'Nexivo Audit',
        subtitle: 'AI audit platform — live at audit-nexivo.vercel.app',
        description: 'B2B audit platform for Indian SMEs. AI-generated audit checklists, smart questions, PDF report generation, business health ratings. Designed for ops managers and consultants to run structured audits without manual setup. React + Vercel + Claude API. Live production deployment.',
        tags: ['React', 'Claude API', 'PDF Reports', 'B2B', 'Vercel', 'Live', 'Nexivo'],
        year: '2026',
        link: 'https://audit-nexivo.vercel.app',
        liveUrl: 'https://audit-nexivo.vercel.app',
        imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'sme-os',
        title: 'SME-OS Multi-Agent System',
        subtitle: 'Python multi-agent outreach automation for B2B lead generation',
        description: 'Multi-agent outreach automation system targeting textile and manufacturing SMEs. Three agents: Agent1 scrapes company data (India + global), Agent2 finds accelerator/funding opportunities (F6S priority), Agent3 finds job roles. Claude Haiku for worker logic, Sonnet for content generation. Outputs to Google Sheets Outreach_Tracker. Gmail OAuth for automated personalized email drafting and send. Expanding to multi-industry.',
        tags: ['Python', 'Claude API', 'Multi-Agent', 'Google Sheets', 'Gmail OAuth', 'Automation'],
        year: '2026',
        link: 'https://github.com/challanamuskan',
        imageUrl: 'https://images.unsplash.com/photo-1611746872915-64382b5c76da?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'nsc',
        title: 'NSC B2B Catalogue',
        subtitle: 'React website for a textile machinery parts dealer',
        description: 'Full B2B product catalogue and lead generation website for National Sales Corporation. Animated SVG logo, 7-category product catalogue (loom parts, spinning spares, bearings, knitting components), RFQ inquiry form, AI chatbot. React + TypeScript + Vite.',
        tags: ['React', 'TypeScript', 'Vite', 'B2B', 'Lead Generation', 'Textile'],
        year: '2025',
        link: 'https://github.com/challanamuskan',
        imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'pitpilot',
        title: 'PitPilot F1 AI',
        subtitle: 'AI-powered Formula 1 pit stop and race strategy assistant',
        description: 'AI-driven analytics dashboard for Formula 1 race operations. Recommends optimal pit stop windows, tyre strategies, and overtaking opportunities based on live race data. Built with Python and data visualisation libraries.',
        tags: ['Python', 'AI', 'Data Analytics', 'F1', 'Strategy'],
        year: '2025',
        link: 'https://github.com/challanamuskan/PitPilot-AI-Driven-Race-Ops-Pit-Strategy-Assistant',
        imageUrl: 'https://images.unsplash.com/photo-1504707748692-419802cf939d?q=80&w=2047&auto=format&fit=crop',
      },
      {
        id: 'legal',
        title: 'Student Legal Gateway',
        subtitle: 'AI legal assistant for international students',
        description: 'RAG-based AI assistant helping international students understand visa conditions, legal rights, and university policies in plain English. Uses vector search and conversational AI to answer complex legal questions instantly.',
        tags: ['RAG', 'AI', 'Python', 'Legal Tech', 'Students'],
        year: '2025',
        link: 'https://github.com/challanamuskan/uni_student_help',
        imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'indian-sme-crm-template',
        title: 'Indian SME CRM Template',
        subtitle: 'Open-source plug-and-play CRM for Indian businesses',
        description: 'Production-ready CRM for Indian SMEs — GST invoices, compliance calendar, WhatsApp broadcast, stock manager, business intelligence dashboard, smart reminders. 11 modules. Config-driven, deploys in 5 minutes on Streamlit Cloud.',
        tags: ['Python', 'Streamlit', 'Supabase', 'GST', 'WhatsApp', 'Open Source'],
        year: '2026',
        link: 'https://github.com/challanamuskan/indian-sme-crm-template',
        liveUrl: 'https://crm-template.streamlit.app',
        imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
      },
    ],
  },
  {
    title: 'Experience',
    items: [
      {
        id: 'nexivo-founder',
        title: 'Founder — Nexivo',
        subtitle: 'DPIIT-Registered Startup · Jaipur, Rajasthan · 2026–Present',
        description: 'Founded Nexivo — a B2B tech ops company for Indian SMEs. DPIIT-registered. Three products: Nexivo CRM (pipeline automation, WhatsApp + email, reporting), Nexivo Audit (AI audit platform, PDF reports, health ratings), Nexivo Automate (workflow automation). 2 paying clients within 3 months. Bootstrapped from zero coding background using AI-assisted development.',
        tags: ['Founder', 'DPIIT Registered', 'B2B SaaS', 'Bootstrapped', '2 Paying Clients'],
        year: '2026–Present',
        imageUrl: 'https://images.unsplash.com/photo-1664575602276-acd073f104c1?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'freelance',
        title: 'Freelance AI Builder',
        subtitle: 'Independent · Jaipur, Rajasthan · 2025–2026',
        description: 'Built AI-powered business tools for SMEs before founding Nexivo. Delivered a live production CRM for a 30-year-old Jaipur manufacturing business and a B2B catalogue website. Used Claude, Cursor, and Gemini for AI-assisted development.',
        tags: ['AI Tools', 'CRM', 'Freelance', 'Python', 'React'],
        year: '2025–2026',
        imageUrl: 'https://images.unsplash.com/photo-1664575602276-acd073f104c1?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'edcon',
        title: "Campus Ambassador — eDCon'26",
        subtitle: 'IIT Delhi · 2025–2026',
        description: "Selected as Campus Ambassador for eDCon'26 by IIT Delhi — one of India's premier entrepreneurship and design conferences. Responsible for outreach, registrations, and representing the event at Sabarmati University.",
        tags: ['IIT Delhi', 'Campus Ambassador', 'Entrepreneurship', 'Leadership'],
        year: '2025–2026',
        imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=2086&auto=format&fit=crop',
      },
      {
        id: 'lagardere',
        title: 'Sales & Marketing Coordinator',
        subtitle: 'Lagardère AWPL · Adelaide, Australia · 2022–2024',
        description: 'Transformed daily customer data into Excel insights, lifting sales by 15%. Cut stock variances by 22% with pivot table inventory optimisation. Boosted upsell rates by 20% with tailored luxury buyer pitches. Built weekly Google Sheets dashboards for real-time team insights.',
        tags: ['Data Analysis', 'Excel', 'Inventory', 'Sales Strategy', 'Australia'],
        year: '2022–2024',
        imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071&auto=format&fit=crop',
      },
      {
        id: 'mentor',
        title: 'Student Mentor',
        subtitle: 'University of South Australia · Adelaide · 2022–2024',
        description: 'Mentored international students navigating Australian university life — academic, cultural, and personal transitions. Part of the formal UniSA peer mentoring programme for 2 years.',
        tags: ['Mentoring', 'Leadership', 'International Students', 'UniSA'],
        year: '2022–2024',
        imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?q=80&w=2070&auto=format&fit=crop',
      },
    ],
  },
  {
    title: 'Achievements',
    items: [
      {
        id: 'dpiit',
        title: 'DPIIT-Registered Startup — Nexivo',
        subtitle: 'Department for Promotion of Industry and Internal Trade · 2026',
        description: 'Nexivo officially recognised as a startup under DPIIT (Department for Promotion of Industry and Internal Trade), Government of India. Enables access to startup India benefits, accelerator eligibility, and government schemes.',
        tags: ['DPIIT', 'Startup India', 'Government Recognition', 'Nexivo'],
        year: '2026',
        modalStyle: 'achievement',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'mckinsey',
        title: 'McKinsey Forward Certified',
        subtitle: 'McKinsey & Company · 2025',
        description: 'Completed McKinsey Forward — a highly selective global programme by McKinsey & Company focused on leadership, structured problem solving, and future-ready professional skills.',
        tags: ['McKinsey', 'Leadership', 'Problem Solving', 'Global', 'Selective'],
        year: '2025',
        modalStyle: 'achievement',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'iim-rohtak',
        title: 'Top 3 — IIM Rohtak National Competition',
        subtitle: 'IIM Rohtak · 2025',
        description: "Secured 3rd place in a national-level competition at IIM Rohtak — one of India's premier management institutes. Competed against participants from top universities across India.",
        tags: ['IIM Rohtak', 'National', 'Top 3', 'Management'],
        year: '2025',
        modalStyle: 'achievement',
        imageUrl: 'https://images.unsplash.com/photo-1523580846011-d3a5bc86b40?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'iit-madras',
        title: 'IIT Madras — SHAastra 2026 × 4',
        subtitle: 'ADI Reverse Engineering · Embedded Programming · E-Contest · Petri Dish',
        description: "Received 4 certificates from SHAastra 2026 — IIT Madras's flagship technical festival. Competed in ADI Reverse Engineering Challenge, Embedded Programming Challenge, E-Contest, and Petri Dish Challenge.",
        tags: ['IIT Madras', 'SHAastra 2026', 'Engineering', 'Technology', '× 4'],
        year: '2026',
        modalStyle: 'achievement',
        imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=2086&auto=format&fit=crop',
      },
      {
        id: 'iit-bombay',
        title: 'IIT Bombay — Techfest 2025 × 2',
        subtitle: "Capture The Flag · Agrowsera TRBS · Asia's Largest Tech Fest",
        description: "2 certificates from Techfest 2025 at IIT Bombay — Asia's largest science and technology festival. Competed in Capture The Flag (cybersecurity) and Agrowsera: The Red Brick Summit agri-innovation challenge.",
        tags: ['IIT Bombay', 'Techfest 2025', "Asia's Largest", 'Cybersecurity', '× 2'],
        year: '2025',
        modalStyle: 'achievement',
        imageUrl: 'https://images.unsplash.com/photo-1581093458791-9a6685c2e505?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'iim-kozhikode',
        title: "IIM Kozhikode — Backwaters'26 × 4",
        subtitle: 'IPL Fantasy · Avatar CEO · Kotler Sutra · Project Horizon',
        description: "4 certificates from Backwaters'26 at IIM Kozhikode — consistently ranked among India's top 5 management institutes. Competed in IPL Fantasy: Build Your Dream Team, Avatar: The Ultimate CEO, Kotler Sutra Marketing Case Competition, and Project Horizon: GPAI Case Competition.",
        tags: ['IIM Kozhikode', "Backwaters'26", 'Marketing', 'Strategy', '× 4'],
        year: '2026',
        modalStyle: 'achievement',
        imageUrl: 'https://images.unsplash.com/photo-1523580846011-d3a5bc86b40?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'iim-indore',
        title: 'IIM Indore — IRIS 2026',
        subtitle: 'Ashwamesha Leadership · Finance League: Equity Pitch',
        description: "Competed in IRIS 2026 — IIM Indore's flagship management fest. Events: Ashwamesha Legacy Leadership Competition and Finance League: Equity Pitch Challenge.",
        tags: ['IIM Indore', 'IRIS 2026', 'Leadership', 'Finance', 'Equity'],
        year: '2026',
        modalStyle: 'achievement',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'unstop',
        title: '83 Competition Certificates — Unstop',
        subtitle: 'IITs · IIMs · Hackathons · Case Studies · 2025–2026',
        description: '83 verified participation certificates on Unstop — spanning hackathons at IIT Madras and IIT Bombay, case competitions at IIM Kozhikode, IIM Indore and IIM Rohtak, national data analytics challenges, cybersecurity contests, HR hackathons, startup pitch events, and marketing case studies.',
        tags: ['83 Certificates', 'IIT', 'IIM', 'Hackathons', 'National', 'Verified'],
        year: '2025–2026',
        modalStyle: 'achievement',
        imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'swimming',
        title: 'Represented India — Freestyle Swimming',
        subtitle: 'National-Level Competitive Athlete · International Competition',
        description: 'National-level competitive freestyle swimmer. Represented India at international competitions. Selected at the highest national level.',
        tags: ['Swimming', 'India', 'International', 'Athlete', 'Freestyle'],
        year: '2014–2016',
        modalStyle: 'achievement',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b17415?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'kathak',
        title: 'Represented India — Classical Kathak',
        subtitle: 'International Performance · Classical Arts',
        description: "Represented India in classical Kathak dance at international performances. Performed on international stages representing India's classical arts tradition.",
        tags: ['Kathak', 'Classical Dance', 'India', 'International', 'Arts'],
        year: '2012–2014',
        modalStyle: 'achievement',
        imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=2069&auto=format&fit=crop',
      },
    ],
  },
  {
    title: 'Certifications',
    items: [
      {
        id: 'cert-mckinsey',
        title: 'McKinsey Forward',
        subtitle: 'McKinsey & Company · 2025',
        description: 'Highly selective global leadership and problem-solving programme by McKinsey & Company.',
        tags: ['McKinsey', 'Leadership', 'Global', 'Selective'],
        year: '2025',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'cert-nestle',
        title: 'Nestlé YEP Academy × 4',
        subtitle: 'Nestlé Young Entrepreneurs Program · 2023–2024',
        description: '4 certifications from Nestlé Young Entrepreneurs Program Academy: Idea Generation, Solution Creation, Successful Entrepreneur, and Food Product Development.',
        tags: ['Nestlé', 'YEP', 'Idea Generation', 'Entrepreneurship', '× 4'],
        year: '2023–2024',
        imageUrl: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'cert-google',
        title: 'Google Data Analytics',
        subtitle: 'Google via Coursera · 2022',
        description: 'Professional certificate covering data cleaning, analysis, visualisation, and storytelling using SQL, R, and Tableau.',
        tags: ['Google', 'Data Analytics', 'SQL', 'R', 'Coursera'],
        year: '2022',
        imageUrl: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?q=80&w=2027&auto=format&fit=crop',
      },
      {
        id: 'cert-cisco',
        title: 'Cisco Networking Academy × 7',
        subtitle: 'Cisco · 2025',
        description: '7 certifications: Networking Basics, Data Analytics Essentials, SQL Basics, Transforming Data with Excel, Dashboarding Basics, Ethical Use of Data, Project Portfolio.',
        tags: ['Cisco', 'SQL', 'Analytics', 'Excel', 'Networking', '× 7'],
        year: '2025',
        imageUrl: 'https://images.unsplash.com/photo-1593435713583-2effa2f6472f?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'cert-hp',
        title: 'HP LIFE × 2',
        subtitle: 'HP Foundation · 2025',
        description: "Data Science & Analytics and AI for Business Professionals — HP Foundation's global learning platform.",
        tags: ['HP LIFE', 'AI', 'Data Science', 'Business'],
        year: '2025',
        imageUrl: 'https://images.unsplash.com/photo-1677756119517-756a188d2d94?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'cert-unstop',
        title: '83 Competition Certificates — Unstop',
        subtitle: 'IITs · IIMs · Hackathons · Case Studies · 2025–2026',
        description: '83 verified participation certificates from competitions hosted by IIT Madras, IIT Bombay, IIM Kozhikode, IIM Indore, IIM Rohtak, plus national hackathons, data analytics challenges, and startup pitch events.',
        tags: ['83 Certificates', 'IIT', 'IIM', 'Hackathons', 'Verified'],
        year: '2025–2026',
        imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=2070&auto=format&fit=crop',
      },
    ],
  },
  {
    title: 'Education',
    items: [
      {
        id: 'vgu-mca',
        title: 'Vivekananda Global University',
        subtitle: 'MCA — Master of Computer Applications · Distance Mode · 2026–2028',
        description: 'Master of Computer Applications (distance mode). Focused on software systems, databases, and emerging technologies. Running in parallel with active startup and freelance work.',
        tags: ['MCA', 'Computer Applications', 'Distance', 'VGU', 'Jaipur'],
        year: '2026–2028',
        imageUrl: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?q=80&w=2074&auto=format&fit=crop',
      },
      {
        id: 'sabarmati',
        title: 'Sabarmati University',
        subtitle: 'B.Com — Bachelor of Commerce · Jaipur, Rajasthan · Graduated 2025',
        description: 'Bachelor of Commerce. Strong foundation in business, economics, finance, and management. Supplemented with extensive competitive participation at IITs and IIMs across India.',
        tags: ['B.Com', 'Business', 'Economics', 'Finance', 'Rajasthan'],
        year: '2022–2025',
        imageUrl: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?q=80&w=2074&auto=format&fit=crop',
      },
      {
        id: 'australia',
        title: 'International Experience — Adelaide, Australia',
        subtitle: 'Adelaide, Australia · 2022–2025',
        description: 'Three years of independent living and professional work experience in Australia. Worked at Lagardère AWPL (Sales & Marketing) and as a UniSA Student Mentor. Returned to India July 2025.',
        tags: ['Australia', 'International Experience', 'Adelaide', 'Cross-Cultural', 'Independent'],
        year: '2022–2025',
        imageUrl: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?q=80&w=2070&auto=format&fit=crop',
      },
    ],
  },
  {
    title: 'Skills',
    items: [
      {
        id: 'skill-ai-llm',
        title: 'AI & LLM',
        subtitle: 'Claude API, Gemini API, OpenAI API, RAG, multi-agent systems',
        description: 'Claude API, Gemini API, OpenAI API, RAG pipelines, vector search, prompt engineering, multi-agent orchestration (Haiku + Sonnet hybrid), LangChain (basics)',
        tags: ['Claude API', 'Gemini API', 'OpenAI API', 'RAG', 'Multi-Agent', 'LangChain'],
        imageUrl: '',
      },
      {
        id: 'skill-rapid-ai-prototyping',
        title: 'Rapid AI Prototyping',
        subtitle: 'Claude, Cursor, GitHub Copilot',
        description: 'Claude, Cursor, GitHub Copilot — iterative AI-assisted development for production apps. Shipped live B2B SaaS from zero coding background in under 3 months.',
        tags: ['Claude', 'Cursor', 'GitHub Copilot', 'AI-assisted Development', 'Rapid Build'],
        imageUrl: '',
      },
      {
        id: 'skill-languages-frameworks',
        title: 'Languages & Frameworks',
        subtitle: 'Python, JavaScript, TypeScript, React, Vite, Streamlit',
        description: 'Python, JavaScript, TypeScript, React, Vite, Streamlit',
        tags: ['Python', 'JavaScript', 'TypeScript', 'React', 'Vite', 'Streamlit'],
        imageUrl: '',
      },
      {
        id: 'skill-apis-deployment',
        title: 'APIs & Deployment',
        subtitle: 'Supabase PostgreSQL, Google APIs, WhatsApp Business API, Vercel',
        description: 'Supabase PostgreSQL, Google Sheets API, Gmail API (OAuth), WhatsApp Business API, Vercel, GitHub',
        tags: ['Supabase', 'Google Sheets API', 'Gmail API', 'WhatsApp API', 'Vercel'],
        imageUrl: '',
      },
      {
        id: 'skill-data-analytics',
        title: 'Data & Analytics',
        subtitle: 'pandas, matplotlib, Excel, SQL, dashboards',
        description: 'Python (pandas, matplotlib), Advanced Excel, SQL basics, Google Sheets dashboards, MIS reporting',
        tags: ['Python', 'pandas', 'matplotlib', 'Advanced Excel', 'SQL', 'Dashboards'],
        imageUrl: '',
      },
      {
        id: 'skill-business',
        title: 'Business & Strategy',
        subtitle: 'Product management, B2B sales, SME operations, startup development',
        description: 'Product thinking, B2B client management, SME operations, accelerator applications, McKinsey structured problem-solving framework',
        tags: ['Product Management', 'B2B', 'SME Ops', 'McKinsey Framework', 'Startup'],
        imageUrl: '',
      },
    ],
  },
  {
    title: 'Volunteering',
    items: [
      {
        id: 'vol-ngo',
        title: 'NGO Volunteer',
        subtitle: 'Rajasthan, India · 2024–2025',
        description: 'Contributed time to community development and education initiatives across Rajasthan. Worked with local NGOs supporting underprivileged communities.',
        tags: ['NGO', 'Community', 'Education', 'Rajasthan'],
        year: '2024–2025',
        imageUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=2070&auto=format&fit=crop',
      },
      {
        id: 'vol-mentor',
        title: 'University Mentor',
        subtitle: 'University of South Australia · 2022–2024',
        description: 'Mentored international students navigating Australian university life through academic and cultural transitions for 2 years.',
        tags: ['Mentoring', 'UniSA', 'International Students', 'Leadership'],
        year: '2022–2024',
        imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=2069&auto=format&fit=crop',
      },
    ],
  },
];
